ALTER TABLE "Order" ADD COLUMN "subtotal" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN "discountTotal" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN "refundTotal" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "Order" ADD COLUMN "refundedAt" TIMESTAMP(3);

ALTER TABLE "OrderItem" ADD COLUMN "discountAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "OrderItem" ADD COLUMN "refundAmount" DOUBLE PRECISION NOT NULL DEFAULT 0;

UPDATE "Order"
SET "subtotal" = "total"
WHERE "subtotal" = 0 AND "total" <> 0;
